image: docker:28

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  # Where to publish this build's tagged working container.
  DOCKER_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  DOCKER_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  DOCKER_LATEST: $CI_REGISTRY_IMAGE:latest

services:
  - docker:28-dind # Needed when building docker images, like the build-docker job

stages:
  - test
  - release

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.test-package:
  image: ghcr.io/astral-sh/uv:python3.13-alpine
  stage: test
  before_script:
    - python -V
    - uv --version
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - uv cache prune --ci
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install -r pyproject.toml --extra dev --extra test
    - uv pip install -e .
    - uv run pytest tests
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .uv-cache
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

release-package:
  image: ghcr.io/astral-sh/uv:python3.13-alpine
  stage: release
  before_script:
    - python -V
    - uv --version
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - uv cache prune --ci
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install build twine flit
    - uv build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .uv-cache
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

release-package-exe:
  stage: release
  tags:
    - windows
  image: python:3.12-windowsservercore-ltsc2022
  script:
    - powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
    - uvx pyinstaller src/rsio/__main__.py --onefile -n rsio
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

.upload-binaries:
  stage: release
  image: python:3.12
  script:
    - echo "Uploading executable to release"
  dependencies:
    - release-rsio-exe
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

.build-docker:
  stage: release
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk update && apk add git
    - docker pull $DOCKER_BRANCH || true
    - docker build --cache-from $DOCKER_BRANCH -f ./Dockerfile --tag $DOCKER_BRANCH .
    - docker push $DOCKER_BRANCH
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

.build-tagged-docker:
  stage: release
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk update && apk add git
    - docker pull $DOCKER_BRANCH || true
    - docker tag $DOCKER_BRANCH $DOCKER_LATEST
    - docker push $DOCKER_LATEST
    - docker tag $DOCKER_BRANCH $DOCKER_TAG
    - docker push $DOCKER_TAG
  rules:
    - if: $CI_COMMIT_TAG

pages:
  image: ghcr.io/astral-sh/uv:python3.13-alpine
  stage: release
  before_script:
    - python -V
    - uv --version
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - uv cache prune --ci
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install -r pyproject.toml --all-extras
    - uv pip install -e .
    - uv run sphinx-build -b html ./docs public
  artifacts:
    paths:
      - public
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - .uv-cache
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
